# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4bee5b260bedd5216f17c987c8a4189"
name = "stock-alert"
handle = "stock-alert-14"
application_url = "https://fed-money-delivery-jet.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stock-alert-test1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://fed-money-delivery-jet.trycloudflare.com/auth/callback",
  "https://fed-money-delivery-jet.trycloudflare.com/auth/shopify/callback",
  "https://fed-money-delivery-jet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
