# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b472b119e2c0bab4004ca596ef64b7b"
name = "stock-alert-new"
handle = "stock-alert-new"
application_url = "https://salary-truly-distances-ingredients.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stock-alert-test1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://salary-truly-distances-ingredients.trycloudflare.com/auth/callback",
  "https://salary-truly-distances-ingredients.trycloudflare.com/auth/shopify/callback",
  "https://salary-truly-distances-ingredients.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
